[package]
name = "goldrust"
version = "0.1.0"
edition = "2021"

[dependencies]
tracing = { version = "0.1.40", features = ["log"] }

[dev-dependencies]
tracing-subscriber = { version = "0.3.18", features = ["env-filter"] }
tokio = { version = "1.40.0", features = ["full"] }

wiremock = "0.6.2"
reqwest = { version = "0.12.7" }